version: "3.1"
services:
    www:
        build: .
        image: daw/lamp-apache-php8:1.0
        ports: 
            - "8001:80"
        volumes:
            - ./www:/var/www/html
        depends_on:
            - db
        networks:
            - lamp-network
    db:
        image: mysql:8.0
        container_name: mysql-lamp-8.0
        ports: 
            - "3390:3306"
        command: --default-authentication-plugin=mysql_native_password
        environment:
            MYSQL_DATABASE: dbname
            MYSQL_PASSWORD: test
            MYSQL_ROOT_PASSWORD: test 
        volumes:
            - ./dump:/docker-entrypoint-initdb.d
            - ./conf:/etc/mysql/conf.d
            - db_data:/var/lib/mysql
        networks:
            - lamp-network

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        depends_on: 
            - db
        networks:
            - lamp-network
        ports:
            - 8000:80
        
        environment:
            MYSQL_USER: root
            MYSQL_PASSWORD: test
            MYSQL_ROOT_PASSWORD: test 
volumes:
    db_data: 
       driver: local

networks:
    lamp-network:
        driver: bridge
       